import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mountProgressionUI } from '../integrations/progression-ui.mjs';
class Node {
 constructor(tag,doc){this.tag=tag;this.ownerDocument=doc;this.children=[];this.events={};this.attrs={};this.isConnected=true;this._text='';}
 set textContent(v){this._text=String(v);this.children=[];} get textContent(){return this._text+this.children.map(c=>c.textContent).join(' ');}
 append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this._text='';this.children=nodes;} setAttribute(k,v){this.attrs[k]=v;} addEventListener(k,v){this.events[k]=v;} focus(){this.ownerDocument.activeElement=this;} showModal(){this.open=true;} close(){this.open=false;} remove(){this.isConnected=false;}
}
function setup(){const doc={createElement(tag){return new Node(tag,doc);}};const root=new Node('main',doc);return {root,ui:mountProgressionUI({element:root}),doc};}
const find=(n,tag)=>n.tag===tag?n:n.children.map(c=>find(c,tag)).find(Boolean);
test('locked hidden achievement never exposes supplied secret text or progress',()=>{const {root,ui}=setup();ui.renderAchievements([{hidden:true,name:'secret title',description:'secret criteria',progress:1,target:9}]);assert.doesNotMatch(root.textContent,/secret|1 of 9/);ui.showAchievement({hidden:true,name:'secret title'});assert.doesNotMatch(root.textContent,/secret/);ui.showAchievement({hidden:true,name:'revealed',unlocked:true});assert.match(root.textContent,/revealed/);});
test('leaderboard privacy is opt-in; unknown provenance remains client-reported',()=>{const {root,ui}=setup();ui.renderLeaderboard({provenance:'trusted-browser',entries:[{visibility:'private',displayName:'Private identity',score:9},{displayName:'Missing consent',score:8},{visibility:'public',displayName:'Public identity',score:7}]});assert.doesNotMatch(root.textContent,/Private identity|Missing consent/);assert.match(root.textContent,/Public identity/);assert.match(root.textContent,/not verified/);});
test('untrusted strings are text only and level stays game scoped',()=>{const {root,ui}=setup();ui.renderAchievements([{name:'<img onerror=alert(1)>',description:'https://example.com'}]);assert.equal(find(root,'img'),undefined);assert.equal(find(root,'a'),undefined);ui.renderLevel({level:2,xp:10,nextLevelXP:20});assert.match(root.textContent,/does not change your Attract Mode reputation/);});
test('save conflict never writes before explicit choice; cancellation preserves both',async()=>{const {root,ui}=setup();let writes=0;const p=ui.resolveSaveConflict({onKeepLocal:async()=>writes++,onKeepRemote:async()=>writes++});const dialog=find(root,'dialog');assert.equal(writes,0);dialog.children.filter(c=>c.tag==='button')[2].events.click();assert.equal(await p,'cancelled');assert.equal(writes,0);});
test('double clicking an in-flight choice does not submit twice; failure stays visible',async()=>{const {root,ui}=setup();let writes=0,fail;const p=ui.resolveSaveConflict({onKeepLocal:()=>{writes++;return new Promise((_,reject)=>fail=reject);},onKeepRemote:async()=>{}});const dialog=find(root,'dialog');const button=dialog.children.filter(c=>c.tag==='button')[0];const first=button.events.click();button.events.click();assert.equal(writes,1);fail(Error('secret server stack'));await first;assert.match(dialog.textContent,/Could not save/);assert.doesNotMatch(dialog.textContent,/secret server stack/);dialog.events.cancel({preventDefault(){}});assert.equal(await p,'cancelled');});
test('account disposal clears all private UI and ignores pending success',async()=>{const {root,ui}=setup();let done;const p=ui.resolveSaveConflict({onKeepLocal:()=>new Promise(r=>done=r),onKeepRemote:async()=>{}});const action=find(root,'dialog').children.filter(c=>c.tag==='button')[0].events.click();ui.destroy();assert.equal(await p,'cancelled');done();await action;ui.renderAchievements([{name:'stale identity'}]);assert.equal(root.textContent,'');});

test('connected panel normalizes real API achievements and XP without invented levels or player IDs',async()=>{
 const {connectProgressionPanel}=await import('../integrations/progression-panel.mjs');const {root}=setup();
 const client={progress:async()=>({xp:25,achievements:{finish:{title:'Course finished',description:'Finish a course',unlockedAt:'2026-10-06'}}}),definitions:async()=>({rules:[]}),leaderboard:async()=>({mode:'server_validated',period:'alltime',entries:[{playerId:'private-stable-id',score:9}]}),setScope(){}};
 const panel=connectProgressionPanel({element:root,client});await panel.refresh();assert.match(root.textContent,/25 game XP/);assert.match(root.textContent,/Course finished/);assert.match(root.textContent,/Server-validated/);assert.doesNotMatch(root.textContent,/private-stable-id|level 1/);
});
test('connected conflict refetches latest version but never retries before choice',async()=>{
 const {connectProgressionPanel}=await import('../integrations/progression-panel.mjs');const {root}=setup();let writes=0;const revisions=[];
 const client={writeSave:async(s,v,r)=>{writes++;revisions.push(r);if(writes===1)throw Object.assign(Error('conflict'),{status:409});return {revision:r+1,value:v};},readSave:async()=>({revision:7,value:{level:2}}),setScope(){}};
 const panel=connectProgressionPanel({element:root,client});const result=panel.writeSave('slot',{level:3},1);await new Promise(resolve=>setImmediate(resolve));assert.equal(writes,1);await find(root,'dialog').children.filter(n=>n.tag==='button')[0].events.click();assert.equal((await result).revision,8);assert.deepEqual(revisions,[1,7]);
});
